version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "14268:14268"
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - jaeger

networks:
  jaeger: